github/hooks: Add ibus-commit-common
You can copy .github/hooks/* file to .git/hooks/. with the file
permission '0755'.
This script is useful not to commit invalid commit IDs every time and
leave a temporary version(1.5.00) in source files when a release is
bumped.
Now a tiny spell checking is also added to output a warning of
possible typos but not an error.

Fixes: https://github.com/ibus/ibus/commit/3bbec69
Fixes: https://github.com/ibus/ibus/commit/cac49dc
Fixes: https://github.com/ibus/ibus/commit/5ed9f13
Fixes: https://github.com/ibus/ibus/commit/7c61e22

diff --git a/.github/hooks/post-merge b/.github/hooks/post-merge
--- a/.github/hooks/post-merge
+++ b/.github/hooks/post-merge
@@ -4,7 +4,7 @@
 #
 # ibus - The Input Bus
 #
-# Copyright (c) 2010-2023 Takao Fujiwara <takao.fujiwara1@gmail.com>
+# Copyright (c) 2023 Takao Fujiwara <takao.fujiwara1@gmail.com>
 #
 # This library is free software; you can redistribute it and/or
 # modify it under the terms of the GNU Lesser General Public
@@ -31,58 +31,19 @@
 # but post-merge succeed the last merge so need to run git reset --hard
 # if this script outputs warnings.
 
-REPO="ibus/ibus"
-TMP_VER="1.5.00"
-
-export GIT_PAGER=cat
-
-echo -e "\033[37;1mIBus post-merge\033[0m"
-
-check_commit_message()
-{
-    ID=$1
-    case "$ID" in
-    39b6907) # Ignore old invalid ID.
-        return;;
-    esac
-    # Check files in the current branch only but not cached commits
-    git log --pretty=oneline | grep -q "$ID" || {
-        echo >&2 "Invalid commit ID: $ID"
-        exit 1
-    }
-}
-
-THIS_FILE="$0"
-diff $THIS_FILE .github/hooks/$(basename $THIS_FILE) || {
-    echo >&2 "$THIS_FILE is older than .github/hooks/$(basename $THIS_FILE)"
+. git-sh-setup
+IBUS_HOOK="$GIT_DIR/hooks/ibus-commit-common"
+test -x "$IBUS_HOOK" &&
+    . "$IBUS_HOOK" || {
+    echo >&2 "Not found $IBUS_HOOK"
     exit 1
 }
 
-test "" = "$(git log --pretty=email HEAD^...HEAD |
-    grep '^Signed-off-by: ' |
-    sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
-    echo >&2 Duplicate Signed-off-by lines.
-    exit 1
-}
-
-for ID in $(git log --pretty=email HEAD~100...HEAD |
-    grep '^Fixes: ' | awk '{print $2}')
-do
-    echo "$ID" | grep -q "^http" && {
-        echo $ID | grep -q "$REPO/commit/" && {
-            ID=$(basename $ID)
-            check_commit_message $ID
-        } || :
-    } || {
-        check_commit_message $ID
-    }
-done
-
-git log --pretty=email HEAD^...HEAD | grep -q "^Subject: \[PATCH\] Release" && {
-    FILES=$(grep "Since: $TMP_VER" $(git ls-files))
-    if test x"$FILES" != x ; then
-        echo >&2 "You need to replace $TMP_VER with the releasing version"
-        echo >&2 "$FILES"
-        exit 1
-    fi
-} || :
+check_if_hook_is_latest "$IBUS_HOOK" || exit 1
+git log --pretty=email HEAD^...HEAD | check_signed_off_by || exit 1
+git log --pretty=email HEAD~100...HEAD | check_commit_id_from_stdin || exit 1
+git log --pretty=email HEAD^...HEAD | grep "^Subject: \[PATCH\] Release" |\
+    check_tmp_version || exit 1
+spell_checking << EOF_ENVS_MAIN
+`git log --pretty=email HEAD^...HEAD | grep -Ev "^From|^Date"`
+EOF_ENVS_MAIN
